[tool.poetry]
name = "goit-web-homework-4"
version = "0.1.0"
description = ""
authors = ["Andrii Lypak <say.elsword@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
